add_test([=[VehicleTest.CarDrive]=]  [==[C:/Users/Asus/Documents/CSE 3205,3206(SE)/CSE 3206/Vehicles/build/main_test.exe]==] [==[--gtest_filter=VehicleTest.CarDrive]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VehicleTest.CarDrive]=]  PROPERTIES WORKING_DIRECTORY [==[C:/Users/Asus/Documents/CSE 3205,3206(SE)/CSE 3206/Vehicles/build]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VehicleTest.BikeDrive]=]  [==[C:/Users/Asus/Documents/CSE 3205,3206(SE)/CSE 3206/Vehicles/build/main_test.exe]==] [==[--gtest_filter=VehicleTest.BikeDrive]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VehicleTest.BikeDrive]=]  PROPERTIES WORKING_DIRECTORY [==[C:/Users/Asus/Documents/CSE 3205,3206(SE)/CSE 3206/Vehicles/build]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VehicleTest.TruckDrive]=]  [==[C:/Users/Asus/Documents/CSE 3205,3206(SE)/CSE 3206/Vehicles/build/main_test.exe]==] [==[--gtest_filter=VehicleTest.TruckDrive]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VehicleTest.TruckDrive]=]  PROPERTIES WORKING_DIRECTORY [==[C:/Users/Asus/Documents/CSE 3205,3206(SE)/CSE 3206/Vehicles/build]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[VehicleTest.InvalidType]=]  [==[C:/Users/Asus/Documents/CSE 3205,3206(SE)/CSE 3206/Vehicles/build/main_test.exe]==] [==[--gtest_filter=VehicleTest.InvalidType]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[VehicleTest.InvalidType]=]  PROPERTIES WORKING_DIRECTORY [==[C:/Users/Asus/Documents/CSE 3205,3206(SE)/CSE 3206/Vehicles/build]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  main_test_TESTS VehicleTest.CarDrive VehicleTest.BikeDrive VehicleTest.TruckDrive VehicleTest.InvalidType)
